version: '3.8'
services:
  back_rev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_rev
    ports:
      - "4000:4000"
    environment: 
      - "PORT=4000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back_rev